apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfsclass
  nfs:
    server: <serverIP>
    path: "/home/nitin/nfs"
